### ISSUE TITLE
Server failing with "no keys found"

### ISSUE THREAD

**Issue by djc** [quinn-rs/quinn-interop#6]
As reported by @larseggert in the interop Slack, filing here for better tracking.

See https://interop.seemann.io/logs/2024-04-22T01:36/quinn_neqo/handshake/output.txt.

**Comment by djc** [comment]
Looks like the error is from here:

https://github.com/quinn-rs/quinn-interop/blob/main/quinn-interop/src/server.rs#L221

Which means that the `/certs/priv.key` file was empty or did not contain a PKCS#8-encoded private key. @marten-seemann did something change about your setup? The Quinn code hasn't been changing so I expect something else.

**Comment by marten-seemann** [comment]
https://github.com/quic-interop/quic-interop-runner/pull/373 maybe?

**Comment by djc** [comment]
Thanks -- that seems plausible. Proposed fix in #7.
