### ISSUE TITLE
Local version of QUINN

### ISSUE THREAD

**Issue by Jazkiel** [quinn-rs/quinn-interop#8]
How do I get this to use a locally built version of quinn? I tried pointing the Cargo.toml to that path but it gives some build errors then, particularly related to h3_quinn.

**Comment by djc** [comment]
If you mean you're trying to use Quinn from main with existing versions of h3-quinn, the Quinn API has changed and h3-quinn will need accompanying/matching changes.

**Comment by Jazkiel** [comment]
I saw that h3-quinn currently uses quinn v0.10.2 so I downloaded that release, built it and updated the paths for Cargo.toml but am still facing some build issues. 
Compiling quinn-proto v0.10.2 (/build/quinn-0.10.2/quinn-proto)
   Compiling quinn v0.10.2 (/build/quinn-0.10.2/quinn)
   Compiling h3-quinn-interop v0.0.0 (/build/quinn-interop)
error[E0308]: mismatched types
   --> src/client.rs:185:80
    |
185 |     let (mut driver, send_request) = h3::client::new(h3_quinn::Connection::new(conn)).await?;
    |                                                      ------------------------- ^^^^ expected `h3_quinn::quinn::Connection`, found `quinn::Connection`
    |                                                      |
    |                                                      arguments to this function are incorrect
    |
    = note: `quinn::Connection` and `h3_quinn::quinn::Connection` have similar names, but are actually distinct types
note: `quinn::Connection` is defined in crate `quinn`
   --> /build/quinn-0.10.2/quinn/src/connection.rs:265:1
    |
265 | pub struct Connection(ConnectionRef);
    | ^^^^^^^^^^^^^^^^^^^^^
note: `h3_quinn::quinn::Connection` is defined in crate `quinn`
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/quinn-0.10.2/src/connection.rs:265:1
    |
265 | pub struct Connection(ConnectionRef);
    | ^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `quinn` are being used?
note: associated function defined here
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/h3-quinn-0.0.3/src/lib.rs:41:12
    |
41  |     pub fn new(conn: quinn::Connection) -> Self {
    |            ^^^

error[E0308]: mismatched types
   --> src/server.rs:147:77
    |
147 |     let mut h3_conn = h3::server::Connection::new(h3_quinn::Connection::new(conn))
    |                                                   ------------------------- ^^^^ expected `h3_quinn::quinn::Connection`, found `quinn::Connection`
    |                                                   |
    |                                                   arguments to this function are incorrect
    |
    = note: `quinn::Connection` and `h3_quinn::quinn::Connection` have similar names, but are actually distinct types
note: `quinn::Connection` is defined in crate `quinn`
   --> /build/quinn-0.10.2/quinn/src/connection.rs:265:1
    |
265 | pub struct Connection(ConnectionRef);
    | ^^^^^^^^^^^^^^^^^^^^^
note: `h3_quinn::quinn::Connection` is defined in crate `quinn`
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/quinn-0.10.2/src/connection.rs:265:1
    |
265 | pub struct Connection(ConnectionRef);
    | ^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `quinn` are being used?
note: associated function defined here
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/h3-quinn-0.0.3/src/lib.rs:41:12
    |
41  |     pub fn new(conn: quinn::Connection) -> Self {
    |            ^^^

error[E0599]: no function or associated item named `client` found for struct `h3_quinn::Endpoint` in the current scope
   --> src/client.rs:273:58
    |
273 |     let mut client_endpoint = h3_quinn::quinn::Endpoint::client("[::]:0".parse().unwrap())?;
    |                                                          ^^^^^^ function or associated item not found in `Endpoint`

error[E0308]: mismatched types
   --> src/client.rs:299:5
    |
299 | /     endpoint
300 | |         .connect(addr, auth.host())?
301 | |         .await
302 | |         .map_err(Into::into)
    | |____________________________^ expected `Result<Connection, Box<dyn Error>>`, found `Result<Connection, _>`
    |
    = note: `h3_quinn::quinn::Connection` and `quinn::Connection` have similar names, but are actually distinct types
note: `h3_quinn::quinn::Connection` is defined in crate `quinn`
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/quinn-0.10.2/src/connection.rs:265:1
    |
265 | pub struct Connection(ConnectionRef);
    | ^^^^^^^^^^^^^^^^^^^^^
note: `quinn::Connection` is defined in crate `quinn`
   --> /build/quinn-0.10.2/quinn/src/connection.rs:265:1
    |
265 | pub struct Connection(ConnectionRef);
    | ^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `quinn` are being used?

error[E0308]: mismatched types
   --> src/client.rs:324:5
    |
324 | /     endpoint
325 | |         .connect(addr, auth.host())?
326 | |         .into_0rtt()
327 | |         .map(|x| x.0)
328 | |         .map_err(|_| "0RTT failed".to_string().into())
    | |______________________________________________________^ expected `Result<Connection, Box<dyn Error>>`, found `Result<Connection, _>`
    |
    = note: `h3_quinn::quinn::Connection` and `quinn::Connection` have similar names, but are actually distinct types
note: `h3_quinn::quinn::Connection` is defined in crate `quinn`
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/quinn-0.10.2/src/connection.rs:265:1
    |
265 | pub struct Connection(ConnectionRef);
    | ^^^^^^^^^^^^^^^^^^^^^
note: `quinn::Connection` is defined in crate `quinn`
   --> /build/quinn-0.10.2/quinn/src/connection.rs:265:1
    |
265 | pub struct Connection(ConnectionRef);
    | ^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `quinn` are being used?

error[E0599]: no function or associated item named `with_crypto` found for struct `h3_quinn::quinn::ServerConfig` in the current scope
  --> src/server.rs:70:60
   |
70 |     let mut server_config = h3_quinn::quinn::ServerConfig::with_crypto(Arc::new(crypto));
   |                                                            ^^^^^^^^^^^ function or associated item not found in `ServerConfig`

**Comment by Jazkiel** [comment]
Nvm, just figured it out. I also need to locally point to the h3 and h3-quinn packages as well.
